name: A manual workflow
on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Say hello
        run: echo Hello

      - name: Say something
        run: echo Something

  goodbye:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - uses: actions/checkout@v3

      - name: Say goodbye
        run: echo Goodbye
