on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Say hello
        run: echo Hello

  goodbye:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - uses: actions/checkout@v2

      - name: Say goodbye
        run: echo Goodbye
