name: A workflow triggered on push
on: [push]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Say I am automated
        run: echo I am automated
